const myData = [
        {
          id: '1',
          name: 'One Piece',
          release: 'Monday',
          status: 'Watching',
          obs: 'Anime longo com muitas aventuras.',
          link: 'https://www.crunchyroll.com/one-piece',
          seasons: [12, 24, 12, 8],
        },
        {
          id: '2',
          name: 'Naruto',
          release: 'Monday',
          status: 'Watching',
          obs: 'Clássico de ninja com muita ação e emoção.',
          link: 'https://www.crunchyroll.com/naruto',
          seasons: [26, 20, 30, 25],
        },
        {
          id: '3',
          name: 'Attack on Titan',
          release: 'Sunday',
          status: 'Watching',
          obs: 'NÃO GOSTEI',
          link: 'https://www.crunchyroll.com/attack-on-titan',
          seasons: [12, 24, 12],
        },
        {
          id: '4',
          name: 'Demon Slayer',
          release: 'Saturday',
          status: 'Completed',
          obs: 'Incrível animação com batalhas épicas.',
          link: 'https://www.crunchyroll.com/demon-slayer',
          seasons: [26, 18],
        },
        {
          id: '5',
          name: 'My Hero Academia',
          release: 'Saturday',
          status: 'Watching',
          obs: 'Anime de super-heróis com poderes e escolas.',
          link: 'https://www.crunchyroll.com/my-hero-academia',
          seasons: [13, 25, 24, 24],
        },
        {
          id: '6',
          name: 'Fullmetal Alchemist: Brotherhood',
          release: 'Friday',
          status: 'Completed',
          obs: 'Uma história de alquimia e drama emocionante.',
          link: 'https://www.crunchyroll.com/fullmetal-alchemist-brotherhood',
          seasons: [25, 24, 12],
        },
        {
          id: '7',
          name: 'Dragon Ball Z',
          release: 'Saturday',
          status: 'Completed',
          obs: 'Lutadores poderosos e batalhas intensas.',
          link: 'https://www.crunchyroll.com/dragon-ball-z',
          seasons: [20, 40, 35],
        },
        {
          id: '8',
          name: 'Death Note',
          release: 'Tuesday',
          status: 'Completed',
          obs: 'Suspense psicológico com um jogo de inteligência entre o bem e o mal.',
          link: 'https://www.crunchyroll.com/death-note',
          seasons: [37],
        },
        {
          id: '9',
          name: 'Sword Art Online',
          release: 'Saturday',
          status: 'Watching',
          obs: 'Jogadores presos em um MMORPG de realidade virtual.',
          link: 'https://www.crunchyroll.com/sword-art-online',
          seasons: [25, 24, 24],
        },
        {
          id: '10',
          name: 'One Punch Man',
          release: 'Tuesday',
          status: 'Watching',
          obs: 'Herói extremamente poderoso, que derrota qualquer inimigo com um único soco.',
          link: 'https://www.crunchyroll.com/one-punch-man',
          seasons: [12, 12],
        },
        {
          id: '11',
          name: 'Bleach',
          release: 'Watching',
          status: 'Completed',
          obs: 'Samurai modernos com poderes sobrenaturais e batalhas emocionantes.',
          link: 'https://www.crunchyroll.com/bleach',
          seasons: [20, 30, 24, 25],
        },
        {
          id: '12',
          name: 'Tokyo Ghoul',
          release: 'Thursday',
          status: 'Watching',
          obs: 'Horror e ação com criaturas canibais.',
          link: 'https://www.crunchyroll.com/tokyo-ghoul',
          seasons: [12, 12],
        },
        {
          id: '13',
          name: 'Fairy Tail',
          release: 'Saturday',
          status: 'Watching',
          obs: 'Mágicos e suas aventuras em guildas.',
          link: 'https://www.crunchyroll.com/fairy-tail',
          seasons: [24, 24, 25, 23],
        },
        {
          id: '14',
          name: 'Neon Genesis Evangelion',
          release: 'Monday',
          status: 'Completed',
          obs: 'Mechas e questões filosóficas profundas sobre a humanidade.',
          link: 'https://www.crunchyroll.com/neon-genesis-evangelion',
          seasons: [26],
        },
        {
          id: '15',
          name: 'Cowboy Bebop',
          release: 'Wednesday',
          status: 'Completed',
          obs: 'Futurista, com viagens espaciais e cenas de ação épicas.',
          link: 'https://www.crunchyroll.com/cowboy-bebop',
          seasons: [26],
        },
        {
          id: '16',
          name: 'JoJo’s Bizarre Adventure',
          release: 'Friday',
          status: 'Watching',
          obs: 'Luta contra seres sobrenaturais e lutas muito estilizadas.',
          link: 'https://www.crunchyroll.com/jojos-bizarre-adventure',
          seasons: [26, 39, 38, 12],
        },
        {
          id: '17',
          name: 'Black Clover',
          release: 'Sunday',
          status: 'Watching',
          obs: 'Ação e magia com um personagem principal sem poderes.',
          link: 'https://www.crunchyroll.com/black-clover',
          seasons: [51, 50],
        },
        {
          id: '18',
          name: 'Hunter x Hunter',
          release: 'Tuesday',
          status: 'Completed',
          obs: 'Uma história épica de aventura com caçadores e monstros.',
          link: 'https://www.crunchyroll.com/hunter-x-hunter',
          seasons: [26, 38],
        },
        {
          id: '19',
          name: 'Mob Psycho 100',
          release: 'Wednesday',
          status: 'Watching',
          obs: 'Um psicólogo psíquico e suas aventuras extraordinárias.',
          link: 'https://www.crunchyroll.com/mob-psycho-100',
          seasons: [12, 13],
        },
        {
          id: '20',
          name: 'The Promised Neverland',
          release: 'Saturday',
          status: 'Completed',
          obs: 'Suspense psicológico em um orfanato com segredos sombrios.',
          link: 'https://www.crunchyroll.com/the-promised-neverland',
          seasons: [12, 11],
        },
      ];
    
export default myData;
  